project:
  title: "base_quarto_site_para_github"
  output-dir: docs

editor: visual

format: 
  html:
    code-link: true
    code-copy: true 
    code-fold: true 
    code-summary: "Mostre o código"
    theme: cosmo
    
execute: 
  echo: true
  warning: false
toc: true  # criar o sumario
toc-depth: 2
lang: pt-BR   # define o idioma para portugues
bibliography: references.bib
csl: ipea.csl
citations-hover: true