project:
  title: "base_quarto_site_para_github"
  output-dir: docs

editor: visual

format: 
  html:
    theme: cosmo
    
execute: 
  echo: true
  warning: false
toc: true  # criar o sumario
toc-depth: 2
lang: pt-BR   # define o idioma para portugues
bibliography: references.bib
csl: ipea.csl